/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.zero88.msa.blueprint;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
